# fly.toml app configuration file generated for ganjoor on 2023-06-09T22:43:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ganjoor"
primary_region = "ams"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
